### ISSUE TITLE
How many scotch eggs is too many?

### ISSUE THREAD

**Issue by samisking** [lewisbuttress/ama#1]
Say I go to a pub, I'm a bit peckish from a long walk, and I see scotch eggs on the menu. How many can I order without it being too much?

Thanks.

**Comment by lewisbuttress** [comment]
It's a good question. If there is a variety of scotch eggs on the menu then it's hard not be tempted by variety. I'd probably recommend only one or maximum two. If you're in a group I'd suggest ordering all flavours and sharing 'halfers'. 

The average scotch egg has 300 calories. This nugget of data may tempt you to go for another long way in between sittings.

Most important though, you'll want to find the right beer and egg pairing.

**Comment by samisking** [comment]
Perfect. Just the right amount of info. I may have to ask about common beer/egg pairings in another question at a later date.

**Comment by lewisbuttress** [comment]
Let's refrain from multiple questions in a thread. I've got scotch eggs to eat.
